runtine:
  datasource:
    mysql:
      driverClassName: com.p6spy.engine.spy.P6SpyDriver
      userName: root
      password: 123456
      url: jdbc:p6spy:mysql://127.0.0.1:3306/community2.0?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    pool:
      initialSize: 10
      maxActive: 80
      maxIdle: 60
      minIdle: 10
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 3000
      minEvictableIdleTimeMillis: 300000
      maxPoolPreparedStatementPerConnectionSize: 10
      filters: stat
      defaultReadOnly: false
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      validationQuery: select 1
      timeBetweenLogStatsMillis: 6000
logging:
  file:
    path: root
    name: myboot
jetcache:
  statIntervalMinutes: 15
  areaInCacheName: false
  local:
    default:
      type: linkedhashmap
      keyConvertor: fastjson
      limit: 100
  remote:
    default:
      type: redis
      keyConvertor: fastjson
      valueEncoder: java
      valueDecoder: java
      poolConfig:
        minIdle: 5
        maxIdle: 20
        maxTotal: 50
      host: 127.0.0.1
      port: 6379



